/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author danib
 */
public class BaseN extends javax.swing.JPanel {

    /**
     * Creates new form BaseN
     */
    public BaseN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_baseN = new javax.swing.JPanel();

        pnl_baseN.setBackground(new java.awt.Color(181, 131, 141));
        pnl_baseN.setMaximumSize(new java.awt.Dimension(690, 460));
        pnl_baseN.setMinimumSize(new java.awt.Dimension(690, 460));

        javax.swing.GroupLayout pnl_baseNLayout = new javax.swing.GroupLayout(pnl_baseN);
        pnl_baseN.setLayout(pnl_baseNLayout);
        pnl_baseNLayout.setHorizontalGroup(
            pnl_baseNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        pnl_baseNLayout.setVerticalGroup(
            pnl_baseNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_baseN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_baseN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnl_baseN;
    // End of variables declaration//GEN-END:variables
}
